services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
        - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT:-production}
    container_name: eyespire-frontend
    ports:
      - "80:80"
      - "443:443"  # For HTTPS if needed
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT:-production}
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      # Mount custom nginx config if needed
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount SSL certificates if using HTTPS
      # - ./ssl:/etc/nginx/ssl:ro

  # Optional: Add a reverse proxy for multiple environments
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: eyespire-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #   networks:
  #     - frontend-network

networks:
  frontend-network:
    driver: bridge
    # If you want to connect to external backend
    external: false
